# This file is autogenerated. If you need to change it, edit
# scripts/gen_pci_defs.sh instead.

from .extendedenum import ExtendedEnum


class PCI_CAP_ID(ExtendedEnum):
    _ids = {
        'PM'	: 0x01,
        'VPD'	: 0x03,
        'MSI'	: 0x05,
        'HT'	: 0x08,
        'VNDR'	: 0x09,
        'DBG'	: 0x0A,
        'SSVID'	: 0x0D,
        'SECDEV'	: 0x0F,
        'EXP'	: 0x10,
        'MSIX'	: 0x11,
        'SATA'	: 0x12,
        'AF'	: 0x13,
    }


class PCI_EXT_CAP_ID(ExtendedEnum):
    _ids = {
        'ERR'	: 0x01,
        'VC'	: 0x02,
        'DSN'	: 0x03,
        'PWR'	: 0x04,
        'RCLD'	: 0x05,
        'RCILC'	: 0x06,
        'RCEC'	: 0x07,
        'MFVC'	: 0x08,
        'VC9'	: 0x09,
        'RCRB'	: 0x0A,
        'VNDR'	: 0x0B,
        'CAC'	: 0x0C,
        'ACS'	: 0x0D,
        'ARI'	: 0x0E,
        'ATS'	: 0x0F,
        'SRIOV'	: 0x10,
        'MRIOV'	: 0x11,
        'MCAST'	: 0x12,
        'PRI'	: 0x13,
        'AMD_XXX'	: 0x14,
        'REBAR'	: 0x15,
        'DPA'	: 0x16,
        'TPH'	: 0x17,
        'LTR'	: 0x18,
        'SECPCI'	: 0x19,
        'PMUX'	: 0x1A,
        'PASID'	: 0x1B,
        'DPC'	: 0x1D,
        'L1SS'	: 0x1E,
        'PTM'	: 0x1F,
    }
